# Generated by Django 3.1.2 on 2021-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210505_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(upload_to='tezi_images/articles', verbose_name='Image file'),
        ),
    ]
