# Generated by Django 3.1.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlepost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/comments', verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/articles', verbose_name='Image file'),
        ),
    ]
