# Generated by Django 3.1.2 on 2021-05-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210514_0749'),
        ('flowbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AlterField(
            model_name='chatoutput',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
    ]
