# Generated by Django 3.1.2 on 2021-05-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowbuilder', '0002_auto_20210514_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatinput',
            old_name='user',
            new_name='company',
        ),
    ]
