# Generated by Django 3.1.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowbuilder', '0003_auto_20210514_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinput',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/chatinput', verbose_name='Image file'),
        ),
        migrations.AddField(
            model_name='chatoutput',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/chatoutput', verbose_name='Image file'),
        ),
    ]
