# Generated by Django 3.1.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='image',
        ),
        migrations.AddField(
            model_name='supportfeedback',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='tezi_images/supportfeedback', verbose_name='Image file'),
        ),
    ]
