# Generated by Django 3.1.2 on 2021-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersupport', '0002_auto_20210515_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='tezi_images/supportrequests', verbose_name='Image file'),
        ),
    ]
