# Generated by Django 3.1.2 on 2021-05-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=162, unique=True)),
                ('role', models.CharField(choices=[('TA', 'TEZI ADMIN'), ('CA', 'CUSTOMER USER'), ('CA', 'CLIENT ADMIN'), ('CE', 'CLIENT EMPLOYEE')], default='CU', max_length=2, verbose_name='user role')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='user_images/%Y/%m/%d')),
                ('display_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='display name')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=17, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=1024, verbose_name='physical address')),
                ('client_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='authentication.user')),
            ],
        ),
    ]
