# Generated by Django 3.1.2 on 2021-05-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210501_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adress',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
