# Generated by Django 3.1.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210514_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/profiles/company', verbose_name='Image file'),
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='tezi_images/profiles/staff', verbose_name='Image file'),
        ),
    ]
