# Generated by Django 3.1.2 on 2021-05-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=60)),
                ('companyEmail', models.EmailField(max_length=200, unique=True)),
                ('adress', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('industry', models.CharField(choices=[('entertainment', 'Entertainment'), ('manufacturing', 'Manufactiring'), ('real_estate', 'Real_estate'), ('accommodation services', 'Accommodation services'), ('financial and insurance', 'Financial and Insurance'), ('information and communication', 'Information and Communication')], max_length=100)),
                ('company_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
