# Generated by Django 3.2 on 2021-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companyEmail',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyName',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
