# Generated by Django 3.1.2 on 2021-05-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to='tezi_images/tickets', verbose_name='Image file'),
        ),
    ]
