# Generated by Django 3.1.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.AddField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='tezi_images/ticketsfeedback', verbose_name='Image file'),
        ),
    ]
