# Generated by Django 3.1.2 on 2021-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20210515_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='tezi_images/tickets', verbose_name='Image file'),
        ),
    ]
